# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2019, 7, 29, 16, 30, 25, 665215)),
        ),
    ]
