# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-04 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialBoard', '0002_auto_20190729_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2019, 8, 4, 15, 24, 27, 834344)),
        ),
    ]
